import { describe, expect, it } from 'vitest'

import { generate } from '../src/generate.js'
import type { DocTypeMeta, FieldMeta } from '../src/meta.js'

function meta(name: string, overrides: Partial<DocTypeMeta> = {}): DocTypeMeta {
    return { name, module: 'Custom', istable: false, issingle: false, is_submittable: false, fields: [], ...overrides }
}

function field(fieldname: string, fieldtype: string, overrides: Partial<FieldMeta> = {}): FieldMeta {
    return { fieldname, fieldtype, reqd: false, permlevel: 0, is_virtual: false, mask: false, ...overrides }
}

const header = `// Generated by @frappeforge/codegen. Do not edit: re-run frappeforge-codegen.
// Exclude this file from formatters so \`frappeforge-codegen --check\` stays byte-exact.`

describe('generate', () => {
    it('writes an interface per DocType, the DocTypes map and the Register declaration', () => {
        const result = generate([
            meta('FF Order Item', {
                istable: true,
                fields: [field('item', 'Link', { label: 'Item', options: 'Item', reqd: true })],
            }),
            meta('FF Order', {
                is_submittable: true,
                fields: [
                    field('customer', 'Data', { label: 'Customer', reqd: true }),
                    field('details_section', 'Section Break'),
                    field('items', 'Table', { label: 'Items', options: 'FF Order Item' }),
                ],
            }),
        ])

        expect(result.warnings).toStrictEqual([])
        expect(result.code).toBe(`${header}
import type { FrappeDoc } from '@frappeforge/client'

/** FF Order — module Custom. Submittable. */
export interface FFOrder extends FrappeDoc {
    doctype: 'FF Order'
    name: string
    /** Customer (Data) */
    customer: string
    /** Items (Table → FF Order Item) */
    items: FFOrderItem[]
}

/** FF Order Item — module Custom. Child table. */
export interface FFOrderItem extends FrappeDoc {
    doctype: 'FF Order Item'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Item (Link → Item) */
    item: string
}

/** Every generated DocType, by name. */
export interface DocTypes {
    'FF Order': FFOrder
    'FF Order Item': FFOrderItem
}

declare module '@frappeforge/client' {
    interface Register {
        docTypes: DocTypes
    }
}
`)
    })

    it('leaves out the Register declaration when register is false', () => {
        const { code } = generate([meta('Note')], { register: false })

        expect(code).not.toContain('declare module')
        expect(code.endsWith("export interface DocTypes {\n    'Note': Note\n}\n")).toBe(true)
    })

    it('types an autoincrement name as a number, and says how each DocType is named and kept', () => {
        const { code } = generate([
            meta('FF Counter', { autoname: 'autoincrement' }),
            meta('FF Settings', { issingle: true, module: 'Setup' }),
            meta('FF Log Item', { istable: true, autoname: 'autoincrement' }),
        ])

        expect(code).toContain(
            "/** FF Counter — module Custom. Named by Autoincrement. */\nexport interface FFCounter extends FrappeDoc {\n    doctype: 'FF Counter'\n    name: number\n",
        )
        expect(code).toContain('/** FF Settings — module Setup. Single. */')
        expect(code).toContain('/** FF Log Item — module Custom. Child table. Named by Autoincrement. */')
    })

    it('imports UnknownDoc only when a child table is not generated, and warns', () => {
        const { code, warnings } = generate([
            meta('FF Order', { fields: [field('items', 'Table', { options: 'FF Order Item' })] }),
        ])

        expect(code).toContain("import type { FrappeDoc, UnknownDoc } from '@frappeforge/client'")
        expect(code).toContain('    items: UnknownDoc[]\n')
        expect(warnings).toStrictEqual([
            "DocType 'FF Order', field 'items': the child DocType 'FF Order Item' is not generated, so its rows are typed UnknownDoc.",
        ])
    })

    it('reports warnings in output order: DocTypes by name, fields in form order', () => {
        const { warnings } = generate([
            meta('B', { fields: [field('two', 'Widget'), field('one', 'Gadget')] }),
            meta('A', { fields: [field('three', 'Gizmo')] }),
        ])

        expect(warnings.map((warning) => warning.slice(0, warning.indexOf(':')))).toStrictEqual([
            "DocType 'A', field 'three'",
            "DocType 'B', field 'two'",
            "DocType 'B', field 'one'",
        ])
    })

    it('quotes keys that are not identifiers, and applies rename', () => {
        const { code } = generate(
            [meta('Item', { fields: [field('delivery-date', 'Date', { reqd: true }), field('class', 'Data')] })],
            { rename: { Item: 'ErpItem' } },
        )

        expect(code).toContain("export interface ErpItem extends FrappeDoc {\n    doctype: 'Item'\n")
        expect(code).toContain("    'delivery-date': string\n")
        expect(code).toContain('    class?: string | null\n')
        expect(code).toContain("    'Item': ErpItem\n")
    })

    it('warns about a rename entry for a DocType that is not generated, such as a typo', () => {
        const { code, warnings } = generate([meta('Item'), meta('ToDo')], {
            rename: { Itme: 'ErpItem', ToDo: 'Task' },
        })

        expect(code).toContain('export interface Item extends FrappeDoc {')
        expect(warnings).toStrictEqual([
            "rename: DocType 'Itme' is not generated, so 'ErpItem' is not used. Check the DocType's name.",
        ])
    })

    describe('TSDoc', () => {
        it('adds the description as a second paragraph, keeping its lines', () => {
            const { code } = generate([
                meta('Note', {
                    description: 'A note.\r\n\r\nShared with the team.  ',
                    fields: [field('title', 'Data', { label: 'Title', description: 'First line\u2028second line' })],
                }),
            ])

            expect(code).toContain(`/**
 * Note — module Custom.
 *
 * A note.
 *
 * Shared with the team.
 */
export interface Note`)
            expect(code).toContain(`    /**
     * Title (Data)
     *
     * First line
     * second line
     */
    title?: string | null`)
        })

        it('cannot be closed early by text from the metadata', () => {
            const { code } = generate([
                meta('Note', {
                    description: '*/ export const injected = 1 /*',
                    fields: [field('title', 'Data', { label: 'Title */ evil' })],
                }),
            ])

            expect(code).toContain(' * *\\/ export const injected = 1 /*\n')
            expect(code).toContain('    /** Title *\\/ evil (Data) */\n')
            expect(code.match(/\*\//gu)).toHaveLength(3)
        })

        it('ignores a description that is only whitespace', () => {
            const { code } = generate([meta('Note', { fields: [field('title', 'Data', { description: ' \n ' })] })])

            expect(code).toContain('    /** Data */\n    title?: string | null\n')
        })
    })

    it('rejects an empty list of DocTypes', () => {
        expect(() => generate([])).toThrow(new Error('There are no DocTypes to generate.'))
    })

    it('rejects a DocType given twice, which would make the output depend on order', () => {
        expect(() => generate([meta('Note'), meta('ToDo'), meta('Note')])).toThrow(
            new Error("DocType 'Note' is given more than once."),
        )
    })

    it('rejects two DocTypes with one interface name', () => {
        expect(() => generate([meta('GL Entry'), meta('GL-Entry')])).toThrow(
            "DocTypes 'GL Entry' and 'GL-Entry' would both be named GLEntry.",
        )
    })
})
