// Generated by @frappeforge/codegen. Do not edit: re-run frappeforge-codegen.
// Exclude this file from formatters so `frappeforge-codegen --check` stays byte-exact.
import type { FrappeDoc } from '@frappeforge/client'

/**
 * FF Escaping — module Custom.
 *
 * Text that would end a comment early: *\/ — and a line
 * separator.
 */
export interface FFEscaping extends FrappeDoc {
    doctype: 'FF Escaping'
    name: string
    /** First *\/ value (Data) */
    '1st_value'?: string | null
    /** Delivery Date (Date) — `YYYY-MM-DD` */
    'delivery-date': string
    /** Path (Select) */
    path?: '' | 'C:\\files' | 'it\'s' | 'line\u2028separator' | null
    /**
     * Remarks (Small Text)
     *
     * Line one
     *
     * Line two *\/
     */
    remarks?: string | null
}

/** FF Settings — module Custom. Single. */
export interface ForgeSettings extends FrappeDoc {
    doctype: 'FF Settings'
    name: string
    /** Enabled (Check) */
    enabled: 0 | 1
}

/** Every generated DocType, by name. */
export interface DocTypes {
    'FF Escaping': FFEscaping
    'FF Settings': ForgeSettings
}
