// Generated by @frappeforge/codegen. Do not edit: re-run frappeforge-codegen.
// Exclude this file from formatters so `frappeforge-codegen --check` stays byte-exact.
import type { FrappeDoc, UnknownDoc } from '@frappeforge/client'

/** FF Counter — module Custom. Named by Autoincrement. */
export interface FFCounter extends FrappeDoc {
    doctype: 'FF Counter'
    name: number
    /** Label (Data) */
    label?: string | null
    /** Secret (Password) — holds `*` placeholders; read the value with `frappe.doc.getPassword` */
    secret?: string | null
}

/**
 * FF Kitchen Sink — module Custom. Submittable.
 *
 * One field of every fieldtype, and every way a field can be optional.
 */
export interface FFKitchenSink extends FrappeDoc {
    doctype: 'FF Kitchen Sink'
    name: string
    /**
     * Title (Data)
     *
     * Shown in lists and links.
     */
    title: string
    /** Display Title (Data) — virtual: computed by the server */
    display_title?: string | null
    /** Status (Select) */
    status?: '' | 'Open' | 'Closed' | null
    /** Kind (Select) */
    kind: 'Goods' | 'Services'
    /** Resolution (Select) */
    resolution?: '' | 'Done' | 'Won\'t Fix' | null
    /** Phase (Select) — a placeholder such as `XXXXXXXX` for users without the mask permission */
    phase?: string | null
    /** Choice (Select) */
    choice?: string | null
    /** Priority (Int) */
    priority: number
    /** Quantity (Float) */
    quantity: number
    /** Amount (Currency) */
    amount: number
    /** Discount (Percent) — a placeholder such as `XXXXXXXX` for users without the mask permission */
    discount: number | string
    /** Cost (Currency) — permission level 1 */
    cost?: number
    /** Total (Float) — virtual: computed by the server */
    total?: number
    /** Approved (Check) */
    approved: 0 | 1
    /** Big Counter (Long Int) — exact up to `Number.MAX_SAFE_INTEGER` */
    big_counter?: number | null
    /** Rating (Rating) */
    rating?: number | null
    /** Duration (Duration) — seconds */
    duration?: number | null
    /** Due Date (Date) — `YYYY-MM-DD` */
    due_date?: string | null
    /** Starts On (Datetime) — `YYYY-MM-DD HH:mm:ss[.ffffff]`, site timezone */
    starts_on?: string | null
    /** Start Time (Time) — `HH:mm:ss[.ffffff]`, site timezone */
    start_time?: string | null
    /** Summary (Small Text) */
    summary?: string | null
    /** Notes (Text) */
    notes?: string | null
    /** Long Notes (Long Text) */
    long_notes?: string | null
    /** Body (Text Editor) */
    body?: string | null
    /** HTML Body (HTML Editor) */
    html_body?: string | null
    /** Markdown Body (Markdown Editor) */
    markdown_body?: string | null
    /** Snippet (Code) */
    snippet?: string | null
    /** Assigned To Full Name (Read Only) */
    assigned_to_full_name?: string | null
    /** Secret (Password) — holds `*` placeholders; read the value with `frappe.doc.getPassword` */
    secret?: string | null
    /** Phone (Phone) */
    phone?: string | null
    /** Email (Data, Email) */
    email?: string | null
    /** Category (Autocomplete) */
    category?: string | null
    /** Color (Color) */
    color?: string | null
    /** Barcode (Barcode) */
    barcode?: string | null
    /** Icon (Icon) */
    icon?: string | null
    /** Signature (Signature) */
    signature?: string | null
    /** Attachment (Attach) */
    attachment?: string | null
    /** Image (Attach Image) */
    image?: string | null
    /** Location (Geolocation) */
    location?: string | null
    /** Payload (JSON) */
    payload?: unknown
    /** Assigned To (Link → User) */
    assigned_to?: string | null
    /** Reference Type (Link → DocType) */
    reference_type?: string | null
    /** Reference Name (Dynamic Link, DocType in `reference_type`) */
    reference_name?: string | null
    /** Approval Code (Data) — permission level 1 */
    approval_code?: string | null
    /** Future Value (Future Type) — unknown fieldtype */
    future_value?: unknown
    /** Items (Table → FF Kitchen Sink Item) */
    items: FFKitchenSinkItem[]
    /** Tags (Table MultiSelect → FF Kitchen Sink Tag) */
    tags: FFKitchenSinkTag[]
    /** External Items (Table → FF External Item) */
    external_items: UnknownDoc[]
}

/** FF Kitchen Sink Item — module Custom. Child table. */
export interface FFKitchenSinkItem extends FrappeDoc {
    doctype: 'FF Kitchen Sink Item'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Label (Data) */
    label?: string | null
    /** Qty (Float) */
    qty: number
    /** Done (Check) */
    done: 0 | 1
}

/** FF Kitchen Sink Tag — module Custom. Child table. */
export interface FFKitchenSinkTag extends FrappeDoc {
    doctype: 'FF Kitchen Sink Tag'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Tag (Link → Tag) */
    tag: string
}

/** Every generated DocType, by name. */
export interface DocTypes {
    'FF Counter': FFCounter
    'FF Kitchen Sink': FFKitchenSink
    'FF Kitchen Sink Item': FFKitchenSinkItem
    'FF Kitchen Sink Tag': FFKitchenSinkTag
}

declare module '@frappeforge/client' {
    interface Register {
        docTypes: DocTypes
    }
}
