// Generated by @frappeforge/codegen. Do not edit: re-run frappeforge-codegen.
// Exclude this file from formatters so `frappeforge-codegen --check` stays byte-exact.
import type { FrappeDoc } from '@frappeforge/client'

/** FF Counter — module Custom. Named by Autoincrement. */
export interface FFCounter extends FrappeDoc {
    doctype: 'FF Counter'
    name: number
    /** Label (Data) */
    label?: string | null
    /** Secret (Password) — holds `*` placeholders; read the value with `frappe.doc.getPassword` */
    secret?: string | null
}

/** Packed Item — module Stock. Child table. */
export interface PackedItem extends FrappeDoc {
    doctype: 'Packed Item'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Parent Item (Link → Item) */
    parent_item?: string | null
    /** Item Code (Link → Item) */
    item_code?: string | null
    /** Item Name (Data) */
    item_name?: string | null
    /** Description (Text Editor) */
    description?: string | null
    /** From Warehouse (Link → Warehouse) */
    warehouse?: string | null
    /** To Warehouse (Optional) (Link → Warehouse) */
    target_warehouse?: string | null
    /** Conversion Factor (Float) */
    conversion_factor: number
    /** Qty (Float) */
    qty: number
    /** Rate (Currency) */
    rate: number
    /** UOM (Link → UOM) */
    uom?: string | null
    /** Use Serial No / Batch Fields (Check) */
    use_serial_batch_fields: 0 | 1
    /** Serial and Batch Bundle (Link → Serial and Batch Bundle) */
    serial_and_batch_bundle?: string | null
    /** Supplier delivers to Customer (Check) */
    delivered_by_supplier: 0 | 1
    /** Serial No (Text) */
    serial_no?: string | null
    /** Batch No (Link → Batch) */
    batch_no?: string | null
    /** Actual Batch Quantity (Float) */
    actual_batch_qty: number
    /** Actual Qty (Float) */
    actual_qty: number
    /** Projected Qty (Float) */
    projected_qty: number
    /** Ordered Qty (Float) */
    ordered_qty: number
    /** Packed Qty (Float) */
    packed_qty: number
    /** Incoming Rate (Currency) */
    incoming_rate: number
    /** Picked Qty (Float) */
    picked_qty: number
    /** Page Break (Check) */
    page_break: 0 | 1
    /** Prevdoc DocType (Data) */
    prevdoc_doctype?: string | null
    /** Parent Detail docname (Data) */
    parent_detail_docname?: string | null
}

/** Payment Schedule — module Accounts. Child table. */
export interface PaymentSchedule extends FrappeDoc {
    doctype: 'Payment Schedule'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Payment Term (Link → Payment Term) */
    payment_term?: string | null
    /** Description (Small Text) */
    description?: string | null
    /** Due Date (Date) — `YYYY-MM-DD` */
    due_date: string
    /** Invoice Portion (Percent) */
    invoice_portion: number
    /** Mode of Payment (Link → Mode of Payment) */
    mode_of_payment?: string | null
    /** Due Date Based On (Select) */
    due_date_based_on?: '' | 'Day(s) after invoice date' | 'Day(s) after the end of the invoice month' | 'Month(s) after the end of the invoice month' | null
    /** Credit Days (Int) */
    credit_days: number
    /** Credit Months (Int) */
    credit_months: number
    /** Discount Date (Date) — `YYYY-MM-DD` */
    discount_date?: string | null
    /** Discount (Float) */
    discount: number
    /** Discount Type (Select) */
    discount_type?: '' | 'Percentage' | 'Amount' | null
    /** Discount Validity Based On (Select) */
    discount_validity_based_on?: '' | 'Day(s) after invoice date' | 'Day(s) after the end of the invoice month' | 'Month(s) after the end of the invoice month' | null
    /** Discount Validity (Int) */
    discount_validity: number
    /** Payment Amount (Currency) */
    payment_amount: number
    /** Outstanding (Currency) */
    outstanding: number
    /** Paid Amount (Currency) */
    paid_amount: number
    /** Discounted Amount (Currency) */
    discounted_amount: number
    /** Payment Amount (Company Currency) (Currency) */
    base_payment_amount: number
    /** Outstanding (Company Currency) (Currency) */
    base_outstanding: number
    /** Paid Amount (Company Currency) (Currency) */
    base_paid_amount: number
}

/** Pricing Rule Detail — module Accounts. Child table. */
export interface PricingRuleDetail extends FrappeDoc {
    doctype: 'Pricing Rule Detail'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Pricing Rule (Link → Pricing Rule) */
    pricing_rule?: string | null
    /** Item Code (Data) */
    item_code?: string | null
    /** Margin Type (Data) */
    margin_type?: string | null
    /** Rate or Discount (Data) */
    rate_or_discount?: string | null
    /** Child Docname (Data) */
    child_docname?: string | null
    /** Rule Applied (Check) */
    rule_applied: 0 | 1
}

/** Sales Order — module Selling. Submittable. */
export interface SalesOrder extends FrappeDoc {
    doctype: 'Sales Order'
    name: string
    /** Title (Data) */
    title?: string | null
    /** Series (Select) */
    naming_series: 'SAL-ORD-.YYYY.-'
    /** Customer (Link → Customer) */
    customer: string
    /** Customer Name (Data) */
    customer_name?: string | null
    /** Tax Id (Data) */
    tax_id?: string | null
    /** Order Type (Select) */
    order_type: '' | 'Sales' | 'Maintenance' | 'Shopping Cart'
    /** Date (Date) — `YYYY-MM-DD` */
    transaction_date: string
    /** Delivery Date (Date) — `YYYY-MM-DD` */
    delivery_date?: string | null
    /** Customer's Purchase Order (Data) */
    po_no?: string | null
    /** Customer's Purchase Order Date (Date) — `YYYY-MM-DD` */
    po_date?: string | null
    /** Company (Link → Company) */
    company: string
    /** Skip Delivery Note (Check) */
    skip_delivery_note: 0 | 1
    /** Has Unit Price Items (Check) */
    has_unit_price_items: 0 | 1
    /** Amended From (Link → Sales Order) */
    amended_from?: string | null
    /** Cost Center (Link → Cost Center) */
    cost_center?: string | null
    /** Project (Link → Project) */
    project?: string | null
    /** Currency (Link → Currency) */
    currency: string
    /**
     * Exchange Rate (Float)
     *
     * Rate at which customer's currency is converted to company's base currency
     */
    conversion_rate: number
    /** Price List (Link → Price List) */
    selling_price_list: string
    /** Price List Currency (Link → Currency) */
    price_list_currency: string
    /**
     * Price List Exchange Rate (Float)
     *
     * Rate at which Price list currency is converted to company's base currency
     */
    plc_conversion_rate: number
    /** Ignore Pricing Rule (Check) — permission level 1 */
    ignore_pricing_rule?: 0 | 1
    /** Scan Barcode (Data, Barcode) */
    scan_barcode?: string | null
    /** Last Scanned Warehouse (Data) — virtual: computed by the server */
    last_scanned_warehouse?: string | null
    /** Set Source Warehouse (Link → Warehouse) */
    set_warehouse?: string | null
    /**
     * Reserve Stock (Check)
     *
     * If checked, Stock will be reserved on <b>Submit</b>
     */
    reserve_stock: 0 | 1
    /** Items (Table → Sales Order Item) */
    items: SalesOrderItem[]
    /** Total Quantity (Float) */
    total_qty: number
    /** Total Net Weight (Float) */
    total_net_weight: number
    /** Total (Company Currency) (Currency) */
    base_total: number
    /** Net Total (Company Currency) (Currency) */
    base_net_total: number
    /** Total (Currency) */
    total: number
    /** Net Total (Currency) */
    net_total: number
    /** Tax Category (Link → Tax Category) */
    tax_category?: string | null
    /** Sales Taxes and Charges Template (Link → Sales Taxes and Charges Template) */
    taxes_and_charges?: string | null
    /** Shipping Rule (Link → Shipping Rule) */
    shipping_rule?: string | null
    /** Incoterm (Link → Incoterm) */
    incoterm?: string | null
    /** Named Place (Data) */
    named_place?: string | null
    /** Sales Taxes and Charges (Table → Sales Taxes and Charges) */
    taxes: SalesTaxesandCharges[]
    /** Total Taxes and Charges (Company Currency) (Currency) */
    base_total_taxes_and_charges: number
    /** Total Taxes and Charges (Currency) */
    total_taxes_and_charges: number
    /** Grand Total (Company Currency) (Currency) */
    base_grand_total: number
    /** Rounding Adjustment (Company Currency) (Currency) */
    base_rounding_adjustment: number
    /** Rounded Total (Company Currency) (Currency) */
    base_rounded_total: number
    /**
     * In Words (Company Currency) (Data)
     *
     * In Words will be visible once you save the Sales Order.
     */
    base_in_words?: string | null
    /** Grand Total (Currency) */
    grand_total: number
    /** Rounding Adjustment (Currency) */
    rounding_adjustment: number
    /** Rounded Total (Currency) */
    rounded_total: number
    /** In Words (Data) */
    in_words?: string | null
    /** Advance Paid (Currency) */
    advance_paid: number
    /** Disable Rounded Total (Check) */
    disable_rounded_total: 0 | 1
    /** Apply Additional Discount On (Select) */
    apply_discount_on?: '' | 'Grand Total' | 'Net Total' | null
    /** Additional Discount Amount (Company Currency) (Currency) */
    base_discount_amount: number
    /** Coupon Code (Link → Coupon Code) */
    coupon_code?: string | null
    /** Additional Discount Percentage (Float) */
    additional_discount_percentage: number
    /** Additional Discount Amount (Currency) */
    discount_amount: number
    /** Taxes and Charges Calculation (Text Editor) */
    other_charges_calculation?: string | null
    /** Packed Items (Table → Packed Item) */
    packed_items: PackedItem[]
    /** Pricing Rule Detail (Table → Pricing Rule Detail) */
    pricing_rules: PricingRuleDetail[]
    /** Customer Address (Link → Address) */
    customer_address?: string | null
    /** Address (Small Text) */
    address_display?: string | null
    /** Customer Group (Link → Customer Group) */
    customer_group?: string | null
    /** Territory (Link → Territory) */
    territory?: string | null
    /** Contact Person (Link → Contact) */
    contact_person?: string | null
    /** Contact (Small Text) */
    contact_display?: string | null
    /** Phone (Data, Phone) */
    contact_phone?: string | null
    /** Mobile No (Small Text) */
    contact_mobile?: string | null
    /** Contact Email (Data, Email) */
    contact_email?: string | null
    /** Shipping Address Name (Link → Address) */
    shipping_address_name?: string | null
    /** Shipping Address (Small Text) */
    shipping_address?: string | null
    /** Dispatch Address Name (Link → Address) */
    dispatch_address_name?: string | null
    /** Dispatch Address (Small Text) */
    dispatch_address?: string | null
    /** Company Address Name (Link → Address) */
    company_address?: string | null
    /** Company Address (Small Text) */
    company_address_display?: string | null
    /** Company Contact Person (Link → Contact) */
    company_contact_person?: string | null
    /** Payment Terms Template (Link → Payment Terms Template) */
    payment_terms_template?: string | null
    /** Payment Schedule (Table → Payment Schedule) */
    payment_schedule: PaymentSchedule[]
    /** Terms (Link → Terms and Conditions) */
    tc_name?: string | null
    /** Terms and Conditions Details (Text Editor) */
    terms?: string | null
    /** Status (Select) */
    status: '' | 'Draft' | 'On Hold' | 'To Deliver and Bill' | 'To Bill' | 'To Deliver' | 'Completed' | 'Cancelled' | 'Closed'
    /** Delivery Status (Select) */
    delivery_status?: '' | 'Not Delivered' | 'Fully Delivered' | 'Partly Delivered' | 'Closed' | 'Not Applicable' | null
    /**
     * %  Delivered (Percent)
     *
     * % of materials delivered against this Sales Order
     */
    per_delivered: number
    /**
     * % Amount Billed (Percent)
     *
     * % of materials billed against this Sales Order
     */
    per_billed: number
    /** % Picked (Percent) */
    per_picked: number
    /** Billing Status (Select) */
    billing_status?: '' | 'Not Billed' | 'Fully Billed' | 'Partly Billed' | 'Closed' | null
    /** Sales Partner (Link → Sales Partner) */
    sales_partner?: string | null
    /** Amount Eligible for Commission (Currency) */
    amount_eligible_for_commission: number
    /** Commission Rate (Float) */
    commission_rate: number
    /** Total Commission (Currency) */
    total_commission: number
    /** Sales Team (Table → Sales Team) */
    sales_team: SalesTeam[]
    /** Loyalty Points (Int) */
    loyalty_points: number
    /** Loyalty Amount (Currency) */
    loyalty_amount: number
    /** From Date (Date) — `YYYY-MM-DD` */
    from_date?: string | null
    /** To Date (Date) — `YYYY-MM-DD` */
    to_date?: string | null
    /** Auto Repeat (Link → Auto Repeat) */
    auto_repeat?: string | null
    /** Letter Head (Link → Letter Head) */
    letter_head?: string | null
    /** Group same items (Check) */
    group_same_items: 0 | 1
    /** Print Heading (Link → Print Heading) */
    select_print_heading?: string | null
    /** Print Language (Data) */
    language?: string | null
    /** Is Internal Customer (Check) */
    is_internal_customer: 0 | 1
    /** Ignore Default Payment Terms Template (Check) */
    ignore_default_payment_terms_template: 0 | 1
    /** Represents Company (Link → Company) */
    represents_company?: string | null
    /** Source (Link → Lead Source) */
    source?: string | null
    /** Inter Company Order Reference (Link → Purchase Order) */
    inter_company_order_reference?: string | null
    /** Campaign (Link → Campaign) */
    campaign?: string | null
    /** Party Account Currency (Link → Currency) */
    party_account_currency?: string | null
}

/** Sales Order Item — module Selling. Child table. */
export interface SalesOrderItem extends FrappeDoc {
    doctype: 'Sales Order Item'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Item Code (Link → Item) */
    item_code: string
    /** Customer's Item Code (Data) */
    customer_item_code?: string | null
    /** Ensure Delivery Based on Produced Serial No (Check) */
    ensure_delivery_based_on_produced_serial_no: 0 | 1
    /** Is Stock Item (Check) */
    is_stock_item: 0 | 1
    /** Reserve Stock (Check) */
    reserve_stock: 0 | 1
    /** Delivery Date (Date) — `YYYY-MM-DD` */
    delivery_date?: string | null
    /** Item Name (Data) */
    item_name: string
    /** Description (Text Editor) */
    description?: string | null
    /** Item Group (Link → Item Group) */
    item_group?: string | null
    /** Brand Name (Link → Brand) */
    brand?: string | null
    /** Image (Attach) */
    image?: string | null
    /** Quantity (Float) */
    qty: number
    /** Stock UOM (Link → UOM) */
    stock_uom?: string | null
    /** UOM (Link → UOM) */
    uom: string
    /** UOM Conversion Factor (Float) */
    conversion_factor: number
    /** Qty as per Stock UOM (Float) */
    stock_qty: number
    /** Stock Reserved Qty (in Stock UOM) (Float) */
    stock_reserved_qty: number
    /** Price List Rate (Currency) */
    price_list_rate: number
    /** Price List Rate (Company Currency) (Currency) */
    base_price_list_rate: number
    /** Margin Type (Select) */
    margin_type?: '' | 'Percentage' | 'Amount' | null
    /** Margin Rate or Amount (Float) */
    margin_rate_or_amount: number
    /** Rate With Margin (Currency) */
    rate_with_margin: number
    /** Discount (%) on Price List Rate with Margin (Percent) */
    discount_percentage: number
    /** Discount Amount (Currency) */
    discount_amount: number
    /** Distributed Discount Amount (Currency) */
    distributed_discount_amount: number
    /** Rate With Margin (Company Currency) (Currency) */
    base_rate_with_margin: number
    /** Rate (Currency) */
    rate: number
    /** Amount (Currency) */
    amount: number
    /** Item Tax Template (Link → Item Tax Template) */
    item_tax_template?: string | null
    /** Basic Rate (Company Currency) (Currency) */
    base_rate: number
    /** Amount (Company Currency) (Currency) */
    base_amount: number
    /** Pricing Rules (Small Text) */
    pricing_rules?: string | null
    /** Rate of Stock UOM (Currency) */
    stock_uom_rate: number
    /** Is Free Item (Check) */
    is_free_item: 0 | 1
    /** Grant Commission (Check) */
    grant_commission: 0 | 1
    /** Net Rate (Currency) */
    net_rate: number
    /** Net Amount (Currency) */
    net_amount: number
    /** Net Rate (Company Currency) (Currency) */
    base_net_rate: number
    /** Net Amount (Company Currency) (Currency) */
    base_net_amount: number
    /** Billed Amt (Currency) */
    billed_amt: number
    /** Valuation Rate (Currency) */
    valuation_rate: number
    /** Gross Profit (Currency) */
    gross_profit: number
    /** Supplier delivers to Customer (Check) */
    delivered_by_supplier: 0 | 1
    /** Supplier (Link → Supplier) */
    supplier?: string | null
    /** Weight Per Unit (Float) */
    weight_per_unit: number
    /** Total Weight (Float) */
    total_weight: number
    /** Weight UOM (Link → UOM) */
    weight_uom?: string | null
    /** Source Warehouse (Link → Warehouse) */
    warehouse?: string | null
    /** Customer Warehouse (Optional) (Link → Warehouse) */
    target_warehouse?: string | null
    /** Quotation (Link → Quotation) */
    prevdoc_docname?: string | null
    /** quotation_item (Data) */
    quotation_item?: string | null
    /** Against Blanket Order (Check) */
    against_blanket_order: 0 | 1
    /** Blanket Order (Link → Blanket Order) */
    blanket_order?: string | null
    /** Blanket Order Rate (Currency) */
    blanket_order_rate: number
    /** Qty (Warehouse) (Float) */
    actual_qty: number
    /** Qty (Company) (Float) */
    company_total_stock: number
    /** BOM No (Link → BOM) */
    bom_no?: string | null
    /** Projected Qty (Float) */
    projected_qty: number
    /** Ordered Qty (Float) */
    ordered_qty: number
    /**
     * Planned Quantity (Float)
     *
     * For Production
     */
    planned_qty: number
    /** Production Plan Qty (Float) */
    production_plan_qty: number
    /** Requested Qty (Float) */
    requested_qty: number
    /** Work Order Qty (Float) */
    work_order_qty: number
    /** Delivered Qty (Float) */
    delivered_qty: number
    /**
     * Produced Quantity (Float)
     *
     * For Production
     */
    produced_qty: number
    /** Returned Qty (Float) */
    returned_qty: number
    /** Picked Qty (in Stock UOM) (Float) */
    picked_qty: number
    /** Additional Notes (Text) */
    additional_notes?: string | null
    /** Page Break (Check) */
    page_break: 0 | 1
    /** Item Tax Rate (Code) */
    item_tax_rate?: string | null
    /**
     * Sales Order Date (Date) — `YYYY-MM-DD`
     *
     * Used for Production Plan
     */
    transaction_date?: string | null
    /** Material Request (Link → Material Request) */
    material_request?: string | null
    /** Purchase Order (Link → Purchase Order) */
    purchase_order?: string | null
    /** Material Request Item (Data) */
    material_request_item?: string | null
    /** Purchase Order Item (Data) */
    purchase_order_item?: string | null
    /** Cost Center (Link → Cost Center) */
    cost_center?: string | null
    /** Project (Link → Project) */
    project?: string | null
    /** Subcontracted Quantity (Float) */
    subcontracted_qty: number
    /** Finished Good (Link → Item) */
    fg_item?: string | null
    /** Finished Good Qty (Float) */
    fg_item_qty: number
}

/** Sales Taxes and Charges — module Accounts. Child table. */
export interface SalesTaxesandCharges extends FrappeDoc {
    doctype: 'Sales Taxes and Charges'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Type (Select) */
    charge_type: '' | 'Actual' | 'On Net Total' | 'On Previous Row Amount' | 'On Previous Row Total' | 'On Item Quantity'
    /** Reference Row # (Data) */
    row_id?: string | null
    /** Account Head (Link → Account) */
    account_head: string
    /** Description (Small Text) */
    description: string
    /**
     * Is this Tax included in Basic Rate? (Check)
     *
     * If checked, the tax amount will be considered as already included in the Print Rate / Print Amount
     */
    included_in_print_rate: 0 | 1
    /**
     * Considered In Paid Amount (Check)
     *
     * If checked, the tax amount will be considered as already included in the Paid Amount in Payment Entry
     */
    included_in_paid_amount: 0 | 1
    /** Cost Center (Link → Cost Center) */
    cost_center?: string | null
    /** Project (Link → Project) */
    project?: string | null
    /** Tax Rate (Float) */
    rate: number
    /** Account Currency (Link → Currency) */
    account_currency?: string | null
    /**
     * Net Amount (Currency)
     *
     * Basis for tax calculation
     */
    net_amount: number
    /** Amount (Currency) */
    tax_amount: number
    /** Total (Currency) */
    total: number
    /** Tax Amount After Discount Amount (Currency) */
    tax_amount_after_discount_amount: number
    /**
     * Net Amount (Company Currency) (Currency)
     *
     * Basis for tax calculation
     */
    base_net_amount: number
    /** Amount (Company Currency) (Currency) */
    base_tax_amount: number
    /** Total (Company Currency) (Currency) */
    base_total: number
    /** Tax Amount After Discount Amount (Company Currency) (Currency) */
    base_tax_amount_after_discount_amount: number
    /** Item Wise Tax Detail (Code) */
    item_wise_tax_detail?: string | null
    /** Dont Recompute tax (Check) */
    dont_recompute_tax: 0 | 1
}

/** Sales Team — module Selling. Child table. */
export interface SalesTeam extends FrappeDoc {
    doctype: 'Sales Team'
    name: string
    parent: string
    parentfield: string
    parenttype: string
    /** Sales Person (Link → Sales Person) */
    sales_person: string
    /** Contact No. (Data) */
    contact_no?: string | null
    /** Contribution (%) (Float) */
    allocated_percentage: number
    /** Contribution to Net Total (Currency) */
    allocated_amount: number
    /** Commission Rate (Data) */
    commission_rate?: string | null
    /** Incentives (Currency) */
    incentives: number
}

/** ToDo — module Desk. */
export interface ToDo extends FrappeDoc {
    doctype: 'ToDo'
    name: string
    /** Status (Select) */
    status?: '' | 'Open' | 'Closed' | 'Cancelled' | null
    /** Priority (Select) */
    priority?: '' | 'High' | 'Medium' | 'Low' | null
    /** Color (Color) */
    color?: string | null
    /** Due Date (Date) — `YYYY-MM-DD` */
    date?: string | null
    /** Allocated To (Link → User) */
    allocated_to?: string | null
    /** Description (Text Editor) */
    description: string
    /** Reference Type (Link → DocType) */
    reference_type?: string | null
    /** Reference Name (Dynamic Link, DocType in `reference_type`) */
    reference_name?: string | null
    /** Role (Link → Role) */
    role?: string | null
    /** Assigned By (Link → User) */
    assigned_by?: string | null
    /** Assigned By Full Name (Read Only) */
    assigned_by_full_name?: string | null
    /** Sender (Data, Email) */
    sender?: string | null
    /** Assignment Rule (Link → Assignment Rule) */
    assignment_rule?: string | null
}

/** Every generated DocType, by name. */
export interface DocTypes {
    'FF Counter': FFCounter
    'Packed Item': PackedItem
    'Payment Schedule': PaymentSchedule
    'Pricing Rule Detail': PricingRuleDetail
    'Sales Order': SalesOrder
    'Sales Order Item': SalesOrderItem
    'Sales Taxes and Charges': SalesTaxesandCharges
    'Sales Team': SalesTeam
    'ToDo': ToDo
}
