// `generate()`: DocType metadata → one TypeScript module. The same DocTypes, in any order, always
// give the same bytes, so the module can be committed and compared in CI.

import { toPropertyKey, toStringLiteral, toTypeNames } from './identifiers.js'
import { mapField } from './mapping.js'
import { type DocTypeMeta, isAutoincremented } from './meta.js'

/** Options for {@link generate}. */
export interface GenerateOptions {
    /**
     * Augment `@frappeforge/client`'s `Register` with the generated DocTypes, so `createClient()` is
     * typed with no type argument. Default `true`. Turn it off to pass the map yourself:
     * `createClient<DocTypes>(…)`.
     */
    register?: boolean
    /**
     * Interface names to use instead of the derived ones, by DocType: `{ Item: 'ErpItem' }`. An entry for
     * a DocType that is not generated gives a warning.
     */
    rename?: Readonly<Record<string, string>>
}

/** What {@link generate} returns. */
export interface GenerateResult {
    /** The TypeScript module: LF line endings, one trailing newline. */
    code: string
    /**
     * What was generated but deserves a look, such as an unknown fieldtype typed `unknown`, a child
     * table whose DocType is not generated, or a `rename` entry for a DocType that is not generated.
     */
    warnings: readonly string[]
}

const header = [
    '// Generated by @frappeforge/codegen. Do not edit: re-run frappeforge-codegen.',
    '// Exclude this file from formatters so `frappeforge-codegen --check` stays byte-exact.',
]

/** Comment text that cannot end the comment early, with every line break as `\n`. */
function toDocText(text: string): string {
    return text
        .replace(/\r\n?|[\u2028\u2029]/gu, '\n')
        .split('\n')
        .map((line) => line.trimEnd())
        .join('\n')
        .trim()
        .replaceAll('*/', '*\\/')
}

/** A TSDoc comment: the summary, then the description as a second paragraph. */
function toDocComment(summary: string, description: string | undefined, indent: string): string[] {
    const lines = toDocText(summary).split('\n')
    const details = toDocText(description ?? '')
    if (details !== '') lines.push('', ...details.split('\n'))
    if (lines.length === 1) return [`${indent}/** ${lines.join('')} */`]
    return [
        `${indent}/**`,
        ...lines.map((line) => (line === '' ? `${indent} *` : `${indent} * ${line}`)),
        `${indent} */`,
    ]
}

function describeDocType(meta: DocTypeMeta): string {
    const kinds = [
        ...(meta.istable ? ['Child table.'] : []),
        ...(meta.issingle ? ['Single.'] : []),
        ...(meta.is_submittable ? ['Submittable.'] : []),
        ...(isAutoincremented(meta) ? ['Named by Autoincrement.'] : []),
    ]
    return [`${meta.name} — module ${meta.module}.`, ...kinds].join(' ')
}

/**
 * Generates one TypeScript module from DocType metadata: an interface per DocType, a `DocTypes` map,
 * and — unless `register` is `false` — the augmentation of `Register` that types `@frappeforge/client`.
 *
 * The types follow what Frappe returns. An empty field is left out of a document and is `null` in a
 * list row, so a field that is not mandatory is `field?: T | null`; numbers and checks are always
 * present; a field the user may not read, at a permission level above 0, can be missing. DocTypes are
 * sorted by name and fields keep the form's order, so the output depends only on the input.
 *
 * @param docTypes - The DocTypes to generate, child tables included, each once.
 * @param options - Whether to augment `Register`, and interface names to use instead of the derived ones.
 * @returns The module's code, and warnings for what deserves a look.
 * @throws `Error` when `docTypes` is empty or names a DocType twice, or when an interface name is not
 * usable or is shared by two DocTypes. The message shows the `rename` fix.
 *
 * @example
 * ```ts
 * const { code, warnings } = generate([normalizeDocType(todoRecord)])
 * await writeFile('src/frappe.generated.ts', code)
 * for (const warning of warnings) console.warn(warning)
 * ```
 */
export function generate(docTypes: readonly DocTypeMeta[], options: GenerateOptions = {}): GenerateResult {
    if (docTypes.length === 0) throw new Error('There are no DocTypes to generate.')
    const seen = new Set<string>()
    for (const { name } of docTypes) {
        if (seen.has(name)) throw new Error(`DocType '${name}' is given more than once.`)
        seen.add(name)
    }

    // Code-point order: the same on every machine, unlike `localeCompare`.
    const sorted = [...docTypes].sort((a, b) => (a.name < b.name ? -1 : 1))
    const namedDocTypes = toTypeNames(sorted, options.rename)
    const typeNames = new Map(namedDocTypes.map(([meta, typeName]) => [meta.name, typeName]))

    const warnings = Object.entries(options.rename ?? {})
        .filter(([doctype]) => !seen.has(doctype))
        .map(
            ([doctype, typeName]) =>
                `rename: DocType '${doctype}' is not generated, so '${typeName}' is not used. Check the DocType's name.`,
        )
    let usesUnknownDoc = false
    const interfaces: string[] = []
    for (const [meta, typeName] of namedDocTypes) {
        const lines = [
            ...toDocComment(describeDocType(meta), meta.description, ''),
            `export interface ${typeName} extends FrappeDoc {`,
            `    doctype: ${toStringLiteral(meta.name)}`,
            `    name: ${isAutoincremented(meta) ? 'number' : 'string'}`,
            ...(meta.istable ? ['    parent: string', '    parentfield: string', '    parenttype: string'] : []),
        ]
        for (const field of meta.fields) {
            const mappedField = mapField(meta.name, field, typeNames)
            if (mappedField === undefined) continue
            if (mappedField.warning !== undefined) warnings.push(mappedField.warning)
            if (mappedField.type === 'UnknownDoc[]') usesUnknownDoc = true
            lines.push(
                ...toDocComment(mappedField.summary, field.description, '    '),
                `    ${toPropertyKey(field.fieldname)}${mappedField.optional ? '?' : ''}: ${mappedField.type}${mappedField.nullable ? ' | null' : ''}`,
            )
        }
        lines.push('}')
        interfaces.push(lines.join('\n'))
    }

    const imports = usesUnknownDoc ? 'FrappeDoc, UnknownDoc' : 'FrappeDoc'
    const docTypesInterface = [
        '/** Every generated DocType, by name. */',
        'export interface DocTypes {',
        ...namedDocTypes.map(([meta, typeName]) => `    ${toStringLiteral(meta.name)}: ${typeName}`),
        '}',
    ].join('\n')
    const registerAugmentation = [
        "declare module '@frappeforge/client' {",
        '    interface Register {',
        '        docTypes: DocTypes',
        '    }',
        '}',
    ].join('\n')

    const sections = [
        [...header, `import type { ${imports} } from '@frappeforge/client'`].join('\n'),
        ...interfaces,
        docTypesInterface,
        ...(options.register === false ? [] : [registerAugmentation]),
    ]
    return { code: `${sections.join('\n\n')}\n`, warnings }
}
